### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by farhan-bs23** [flavorly/vanilla-components#100]
Followed the instructions in the Quick Start, development works fine but build fails and 2 errors are shown as below:
![image](https://github.com/flavorly/vanilla-components/assets/99819029/7ba6d94b-966b-43ca-bed1-0c9ff8c79f28)

**Comment by nikuscs** [comment]
Interesting, mind share your env? are you using pnpm or npm to build?

**Comment by farhan-bs23** [comment]
Using npm. I've installed it on a fresh Vue 3 project with Vite.

**Comment by nikuscs** [comment]
This should be fixed in 0.7.60 , thanks for pointing out! In any case i would recommend using pnpm for future builds as its what we use internally. Thanks once again!

**Comment by fleabitten232** [comment]
The 0.7.60 update only appears to have fixed one of the errors -- the 'Unused directive' error remains.

![image](https://github.com/flavorly/vanilla-components/assets/50779896/f5166f4c-8833-4a27-9328-13a17100aa96)
